# Generated by Django 3.1.4 on 2021-01-08 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20210101_0243'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='introduction',
            field=models.CharField(default='Add an introduction for the post!', max_length=400),
        ),
    ]
